#!/bin/bash

# setting via /etc/network/interfaces

STATIC_IP=${1:-"192.168.1.50"}
NETWORK_MASK=${2:-"255.255.255.0"}
NETWORK_GATEWAY=${3:-"192.168.1.1"}

NAMESERVER_PRIMARY=${4:-"8.8.8.8"}
NAMESERVER_SECONDARY=${5:-"4.4.4.4"}

echo "Setting static IP address to: " $STATIC_IP

interface_config="\nauto eth0
\niface eth0 inet static
\n\taddress ${STATIC_IP}
\n\tnetmask ${NETWORK_MASK}
\n\tgateway ${NETWORK_GATEWAY}
\n\tdns-nameservers 4.4.4.4
\n\tdns-nameservers 8.8.8.8"

nameserver_config="# Generated by portal-manager
\nnameserver ${NAMESERVER_PRIMARY}
\nnameserver ${NAMESERVER_SECONDARY}"

# This needs to call relative path from where executed
# echo ./scripts/network/network.config >> /etc/network/interfaces
echo $interface_config >> /etc/network/interfaces
echo $namespace_config > /etc/resolv.conf

# Restart networking
echo "Restarting networkd"
systemctl restart network

echo "DONE: Finished process"

# DEBUGGING
# echo $interface_config >> ./text.txt
# echo $interface_config 