---
- hosts: localhost
  connection: local
  become: yes
  vars_files:
    - ./defaults/main.yml

  tasks:
    - name: Add Influx GPG apt Key
      apt_key:
        url: https://repos.influxdata.com/influxdata-archive_compat.key
        state: present

    - name: Add Influx Repository
      apt_repository:
        repo: deb https://repos.influxdata.com/debian stable main
        state: present

    - name: Update apt and install telegraf
      apt:
        pkg:
          - telegraf
        state: latest
        update_cache: true

    - name: Start telegraf.service
      service:
        name: telegraf
        state: started
    
    - name: Enable telegraf.service to start on boot
      service:
        name: telegraf
        state: enabled

    - name: Write telegraf conig file
      copy:
        dest: "/etc/telegraf/telegraf.conf"
        src: "{{ home_path }}/portal-manager/ansible/assets/telegraf/telegraf.conf"

    - name: Restart telegraf.service
      service:
        name: telegraf
        state: restarted
