---
- hosts: localhost
  connection: local
  become: yes
  vars_files:
    - ./defaults/main.yml

  tasks:    
    - name: Add Influx GPG apt Key
      apt_key:
        url: https://repos.influxdata.com/influxdata-archive_compat.key
        state: present

    - name: Add Influx Repository
      apt_repository:
        # repo: deb https://download.docker.com/linux/ubuntu focal stable
        repo: deb https://repos.influxdata.com/debian stable main
        state: present

    - name: Update apt and install telegraf
      apt:
        # name: docker-ce
        pkg:
          - telegraf
        state: latest
        update_cache: true

    - name: Write netplan conig file
      copy:
        dest: "/etc/telegraf/telegraf.conf"
        src: "{{ home_path }}/portal-manager/ansible/assets/telegraf/telegraf.conf"

    - name: Start telegraf.service
      service:
        name: telegraf
        state: restarted



# influxdata-archive_compat.key GPG Fingerprint: 9D539D90D3328DC7D6C8D3B9D8FF8E1F7DF8B07E
# wget -q https://repos.influxdata.com/influxdata-archive_compat.key
# echo '393e8779c89ac8d958f81f942f9ad7fb82a25e133faddaf92e15b16e6ac9ce4c influxdata-archive_compat.key' | sha256sum -c && cat influxdata-archive_compat.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg > /dev/null
# echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main' | sudo tee /etc/apt/sources.list.d/influxdata.list
# sudo apt-get update && sudo apt-get install telegraf
