---
- hosts: localhost
  connection: local
  become: yes
  tasks:

    - name: Add VS Code GPG apt Key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add VS Code Apt Repository
      apt_repository:
        repo: deb https://packages.microsoft.com/repos/code stable main
        state: present

    - name: Update apt transport https
      apt:
        # name: docker-ce
        pkg:
          - apt-transport-https
        state: latest
        update_cache: true

    - name: Install VS Code   
      apt:
        pkg:
          - code
        state: latest
        update_cache: true
